import React, { FC } from 'react'
import Head from 'next/head'
import Navbar from '../Navbar'


interface Props {
  children?: React.ReactNode;
}

const MainLayout: React.FC<Props> = ({ children }) => {
    return (
        <>
          <Head> 
            <title>Santiago Muñoz B.</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <Navbar/>
          
            <main className="main">
            
                { children }
               
            </main>
          
        </>
      )
}

export default MainLayout